### ISSUE TITLE
On atomic design

### ISSUE THREAD

**Issue by adamkhan** [dennisreimann/website#10]
Thanks for the courage to write this. From the start I thought atomic design was a daft approach; Yandex solved the problem elegantly and universally with BEM, it seems to me, and people's energies would be better spent promoting it instead of coming up with more vivid but flawed alternatives.

Along similar lines, I wonder if commenting on blog posts by adding new issues to a Github repo is also something that we'll soon look back at as bizarre!

**Comment by dennisreimann** [comment]
Thanks for your feedback, Adam :)

Regarding the comments: That‘s something I‘ll try to improve soon.
