### ISSUE TITLE
is_bitstring vs is_binary?

### ISSUE THREAD

**Issue by tielur** [dennisreimann/website#3]
Is there a reason why `is_bitstring/1` is used instead of `is_binary/1` [here](https://github.com/dennisreimann/website/blame/master/src/articles/2017-01-09-phoenix-passwordless-authentication-magic-link.md#L299)?

**Comment by dennisreimann** [comment]
Thanks! No there isn't except me not knowing the language fully enough :)

**Comment by dennisreimann** [comment]
Fixed with 8c6046294ea703bd06ef0eddc068fc6844f23af9 – thanks again :)
