### ISSUE TITLE
I agree! 

### ISSUE THREAD

**Issue by gandhiShepard** [dennisreimann/website#8]
I remember when the Atomic Design article first came out. It was wildly popular. At that time, "modularity" was a hot new concept and the "Atomic" analogy was one that moved the discussion forward. I agree with your "Foundation, Elements, Modules and the Prototype" approach, and I think that it fits much better. 

Again, back when the Atomic Design article came out, we were all still writing out own CSS and HTML. Now BootStrap everything has changed the need to figure things out in this fashion. 

Overall, I like to say that code ages more like bread than wine. The trick is always to strive for solutions that slow down the speed at which our code becomes stale and unmanageable.

**Comment by dennisreimann** [comment]
Thanks for the feedback 👍🏻
