### ISSUE TITLE
Clickbaity headline indeed

### ISSUE THREAD

**Issue by DivinoAG** [dennisreimann/website#9]
My issue with your article is that it treats Atomic Design as a dogmatic approach to design systems and therefore your disagreement with the categorization makes the original "wrong", when in reality it is simply, and this is very important, _one suggested taxonomy_ to categorize design systems.

To quote Brad Frost himself:

> At the end of the day, it’s about choosing conventions that make sense for your team. So if atomic design naming makes sense to apply to code structure, then by all means go for it!

The implication here is that if the specific naming does not make sense, the general methodology of breaking down a design system into different "levels" can still be applied with a naming scheme that makes sense to your project or team. The organization method is the important aspect, not the specific categories or names.

I personally don't even like the Atomic naming scheme very much, I find the Biology analogy to be too abstract and generally unhelpful. I have similar issues with your own suggestion: names like "modules" and "prototypes" are no less broad and abstract than "molecules" or "organisms" in the context of a design system.

After having studied a large number of publicly available design systems, my personal favorite is [GE's Predix system](https://medium.com/ge-design/ges-predix-design-system-8236d47b0891), which does two things I find very helpful:

* it inverts the hierarchy to larger-then-small, as thinking first about "atomic" level components makes sense when building the system, but less sense for the system's end user when developing applications or features.
* it uses a naming scheme that more closely follows the terminology that both designers and developers would use to communicate parts of an application on their day-to-day. You can see their system's categories in the image below:

![GE's Predix system](https://cdn-images-1.medium.com/max/1000/1*nomBq13bCus2wEn1uZ6xtQ.png)

**Comment by dennisreimann** [comment]
Thanks for the feedback, Andre! 😀

**Comment by dennisreimann** [comment]
Thanks for the feedback, Andre! 😀
